name: go ci

on: [push] # Déclencher le workflow lorsque vous poussez du code

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.x # Version de Go que vous souhaitez utiliser

    - name: Build and Test
      run: |
        go build -v ./...
        go test -v ./...
